@startuml uc
left to right direction
actor 教科担当
actor 担任
rectangle 成績管理システム{
usecase 担任ログイン
usecase 学年情報の登録
usecase 学生情報の登録
usecase 成績情報を印刷
usecase 教科担当ログイン
usecase 計算式の編集
usecase 成績を検索
usecase 評価を記入
usecase 個人の成績を表示
usecase 科目ごとの成績を表示
usecase クラス毎の成績を表示
}
教科担当ログイン <-- 教科担当
計算式の編集 <-- 教科担当
評価を記入 <-- 教科担当
個人の成績を表示 --|> 成績を検索
科目ごとの成績を表示 --|> 成績を検索
クラス毎の成績を表示 --|> 成績を検索
成績を検索 <-- 教科担当
担任 --> 学生情報の登録
担任 --> 担任ログイン
担任 --> 学年情報の登録
担任 --> 成績を検索
担任 --> 成績情報を印刷